const {
  getListDB,
  getOneDB,
  getOneKeyDB,
  insertManyDB,
  insertOneDB,
  insertOneTransaction,
  deleteHardOneDB,
  updateOneKeyDB,
  deleteDB,
  deleteOneDB,
  updateFindOneKeyDB,
  getCountDB,
  updateManyDB,
} = require("./mongoQueries");

module.exports = {
  getListDB,
  getOneDB,
  getOneKeyDB,
  insertManyDB,
  insertOneDB,
  insertOneTransaction,
  deleteHardOneDB,
  updateOneKeyDB,
  deleteDB,
  deleteOneDB,
  updateFindOneKeyDB,
  getCountDB,
  updateManyDB,
};
